script: bootstrap should use virtualenv's activate to setup env

diff --git a/{{cookiecutter.project_slug}}/script/bootstrap b/{{cookiecutter.project_slug}}/script/bootstrap
--- a/{{cookiecutter.project_slug}}/script/bootstrap
+++ b/{{cookiecutter.project_slug}}/script/bootstrap
@@ -37,10 +37,11 @@ if [ ! -f "$ENV_DIR/bin/python3" ]; then
 	hash -r >/dev/null 2>&1
 fi
 
+. "${ENV_DIR}/bin/activate"
+
 if ! is_on_path "$ENV_DIR/bin"; then
-	warn '! You should add ".venv/bin" to your PATH. Source .envrc" into your !'
-	warn '! shell, or install direnv or similar tool that will do it for you. !'
-	. .envrc
+	warn 'WARN: Failed to activate'
+	exit 1
 fi
 
 
